
jackal_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

jackal_velocity_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['motor_1', 'motor_2']
  right_wheel: ['motor_3', 'motor_4']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.1
  k_r: 0.1

  enable_odom_tf: false

  wheel_separation_multiplier: 1.5
  wheel_radius_multiplier: 1.0

  linear:
    x:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 20.0

  angular:
    z:
      has_velocity_limits: true
      max_velocity: 4.0
      has_acceleration_limits: true
      max_acceleration: 25.0

gazebo_ros_control:
  pid_gains:
    motor_1:
      p: 1.0
      i: 0.1
      d: 0.01
    motor_2:
      p: 1.0
      i: 0.1
      d: 0.01
    motor_3:
      p: 1.0
      i: 0.1
      d: 0.01
    motor_4:
      p: 1.0
      i: 0.1
      d: 0.01

